# Generated by Django 5.2.5 on 2025-10-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
