# Generated by Django 5.2.5 on 2025-10-29 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alumno_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='alumnocarrera',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='alumnocarrera',
            name='fecha_inscripcion',
        ),
        migrations.RemoveField(
            model_name='alumnomateria',
            name='fecha_inscripcion',
        ),
    ]
